export type Contribution = {
  repo: string;
  number: number;
  kind: "pr" | "issue";
  title: string;
  url: string;
  status: "merged" | "open" | "closed";
  createdAt: string;
};

export const contributionsUpdatedAt = "2026-09-14";

// Public, authored contributions referenced in the local open-source records.
export const contributions: Contribution[] = [
  {
    repo: "open-telemetry/opentelemetry-rust",
    number: 3718,
    kind: "pr",
    title: "feat(trace): support the W3C random trace ID flag",
    url: "https://github.com/open-telemetry/opentelemetry-rust/pull/3718",
    status: "open",
    createdAt: "2026-09-09",
  },
  {
    repo: "vapor/vapor",
    number: 3540,
    kind: "issue",
    title:
      "Empty certificate chain in .inMemory TLS configuration starts the server instead of failing",
    url: "https://github.com/vapor/vapor/issues/3540",
    status: "closed",
    createdAt: "2026-08-27",
  },
  {
    repo: "swiftlang/swift-syntax",
    number: 3411,
    kind: "pr",
    title: "[SwiftSyntaxMacroExpansion] Expand attached macros with module-qualified names",
    url: "https://github.com/swiftlang/swift-syntax/pull/3411",
    status: "merged",
    createdAt: "2026-08-27",
  },
  {
    repo: "open-telemetry/opentelemetry-cpp",
    number: 4462,
    kind: "pr",
    title: "[SDK] Range check the rule based predicate double precision",
    url: "https://github.com/open-telemetry/opentelemetry-cpp/pull/4462",
    status: "merged",
    createdAt: "2026-08-20",
  },
  {
    repo: "usedetail/cli",
    number: 335,
    kind: "pr",
    title: "fix(bugs): clamp page on empty client-side filter results",
    url: "https://github.com/usedetail/cli/pull/335",
    status: "merged",
    createdAt: "2026-08-20",
  },
  {
    repo: "vapor/vapor",
    number: 3516,
    kind: "pr",
    title: "Add support for reloading TLS certificates",
    url: "https://github.com/vapor/vapor/pull/3516",
    status: "merged",
    createdAt: "2026-08-15",
  },
  {
    repo: "vercel-labs/deepsec",
    number: 152,
    kind: "pr",
    title: "Add Grok Build CLI agent backend",
    url: "https://github.com/vercel-labs/deepsec/pull/152",
    status: "open",
    createdAt: "2026-08-12",
  },
  {
    repo: "vercel-labs/deepsec",
    number: 151,
    kind: "issue",
    title: "Agent: Grok Build CLI",
    url: "https://github.com/vercel-labs/deepsec/issues/151",
    status: "open",
    createdAt: "2026-08-12",
  },
  {
    repo: "firecrawl/pdf-inspector",
    number: 336,
    kind: "issue",
    title: "Node bindings block the event loop; async variants?",
    url: "https://github.com/firecrawl/pdf-inspector/issues/336",
    status: "closed",
    createdAt: "2026-08-10",
  },
  {
    repo: "firecrawl/pdf-inspector",
    number: 335,
    kind: "pr",
    title: "Release the GIL during parsing in the Python bindings",
    url: "https://github.com/firecrawl/pdf-inspector/pull/335",
    status: "closed",
    createdAt: "2026-08-10",
  },
  {
    repo: "HCF-STUDIOS/openhermit",
    number: 253,
    kind: "pr",
    title: "Read documents through anydoc and pdf-inspector",
    url: "https://github.com/HCF-STUDIOS/openhermit/pull/253",
    status: "merged",
    createdAt: "2026-08-10",
  },
  {
    repo: "open-telemetry/opentelemetry-cpp",
    number: 4366,
    kind: "pr",
    title: "[CONFIGURATION] Build composable samplers from file configuration",
    url: "https://github.com/open-telemetry/opentelemetry-cpp/pull/4366",
    status: "merged",
    createdAt: "2026-08-05",
  },
  {
    repo: "open-telemetry/opentelemetry-cpp",
    number: 4334,
    kind: "pr",
    title: "[CONFIGURATION] Add the probability sampler to file configuration",
    url: "https://github.com/open-telemetry/opentelemetry-cpp/pull/4334",
    status: "merged",
    createdAt: "2026-08-02",
  },
  {
    repo: "kubestellar/kubeflex",
    number: 707,
    kind: "pr",
    title: "\ud83c\udf31 make the built-in version semver-legal",
    url: "https://github.com/kubestellar/kubeflex/pull/707",
    status: "open",
    createdAt: "2026-07-28",
  },
  {
    repo: "kubestellar/kubeflex",
    number: 702,
    kind: "pr",
    title: "\ud83d\udc1b fix kflex init pulling the operator chart with a truncated version tag",
    url: "https://github.com/kubestellar/kubeflex/pull/702",
    status: "merged",
    createdAt: "2026-07-17",
  },
  {
    repo: "perses/plugins",
    number: 727,
    kind: "pr",
    title: "[DOC] Table: fix format modifier syntax in dynamic links example",
    url: "https://github.com/perses/plugins/pull/727",
    status: "merged",
    createdAt: "2026-07-10",
  },
  {
    repo: "kubestellar/kubeflex",
    number: 693,
    kind: "pr",
    title: "\ud83d\udc1b use current context for kflex create when it accesses the hosting cluster",
    url: "https://github.com/kubestellar/kubeflex/pull/693",
    status: "merged",
    createdAt: "2026-07-08",
  },
  {
    repo: "headlamp-k8s/plugins",
    number: 861,
    kind: "pr",
    title: "flux: fix inventory crash on cluster-scoped resources with a built-in kind name",
    url: "https://github.com/headlamp-k8s/plugins/pull/861",
    status: "open",
    createdAt: "2026-06-26",
  },
  {
    repo: "agones-dev/agones",
    number: 4632,
    kind: "pr",
    title: "build: print debug info on helm install failure",
    url: "https://github.com/agones-dev/agones/pull/4632",
    status: "merged",
    createdAt: "2026-06-23",
  },
  {
    repo: "apple/swift-nio",
    number: 3629,
    kind: "pr",
    title: "[NIOFileSystem] Fall back to non-positional IO on ENXIO for unseekable files",
    url: "https://github.com/apple/swift-nio/pull/3629",
    status: "closed",
    createdAt: "2026-06-18",
  },
  {
    repo: "meshery/meshery",
    number: 20053,
    kind: "pr",
    title: "[UI] Extract shared ResponsiveImage component for extensions",
    url: "https://github.com/meshery/meshery/pull/20053",
    status: "open",
    createdAt: "2026-06-13",
  },
  {
    repo: "agones-dev/agones",
    number: 4618,
    kind: "pr",
    title: "Add AGENTS.md for AI coding agents",
    url: "https://github.com/agones-dev/agones/pull/4618",
    status: "merged",
    createdAt: "2026-06-13",
  },
  {
    repo: "open-telemetry/opentelemetry-cpp",
    number: 4135,
    kind: "pr",
    title: "[SDK] Implement the ProbabilitySampler",
    url: "https://github.com/open-telemetry/opentelemetry-cpp/pull/4135",
    status: "merged",
    createdAt: "2026-06-07",
  },
  {
    repo: "open-telemetry/opentelemetry-swift-core",
    number: 78,
    kind: "pr",
    title: "Log a warning on duplicate instrument registration",
    url: "https://github.com/open-telemetry/opentelemetry-swift-core/pull/78",
    status: "merged",
    createdAt: "2026-06-07",
  },
  {
    repo: "swiftlang/sourcekit-lsp",
    number: 2688,
    kind: "pr",
    title: "Document the 'Add Explicit Raw Values' refactoring action",
    url: "https://github.com/swiftlang/sourcekit-lsp/pull/2688",
    status: "merged",
    createdAt: "2026-06-06",
  },
  {
    repo: "swiftlang/swift-format",
    number: 1215,
    kind: "pr",
    title: "Don't insert trailing commas into attribute argument lists",
    url: "https://github.com/swiftlang/swift-format/pull/1215",
    status: "merged",
    createdAt: "2026-06-06",
  },
  {
    repo: "headlamp-k8s/plugins",
    number: 784,
    kind: "pr",
    title: "cluster-api: implement i18n for all plugin strings",
    url: "https://github.com/headlamp-k8s/plugins/pull/784",
    status: "open",
    createdAt: "2026-06-02",
  },
  {
    repo: "swiftlang/sourcekit-lsp",
    number: 2680,
    kind: "pr",
    title: "Add 'Generate enum associated value accessors' code action",
    url: "https://github.com/swiftlang/sourcekit-lsp/pull/2680",
    status: "merged",
    createdAt: "2026-06-01",
  },
  {
    repo: "headlamp-k8s/plugins",
    number: 780,
    kind: "issue",
    title: "cluster-api: do i18n",
    url: "https://github.com/headlamp-k8s/plugins/issues/780",
    status: "open",
    createdAt: "2026-05-30",
  },
  {
    repo: "headlamp-k8s/plugins",
    number: 777,
    kind: "pr",
    title: "flux: canaries: Fix crash on older Headlamp hosts",
    url: "https://github.com/headlamp-k8s/plugins/pull/777",
    status: "merged",
    createdAt: "2026-05-30",
  },
  {
    repo: "headlamp-k8s/plugins",
    number: 773,
    kind: "pr",
    title: 'flux: fix Next Reconciliation showing "<invalid>"',
    url: "https://github.com/headlamp-k8s/plugins/pull/773",
    status: "merged",
    createdAt: "2026-05-29",
  },
  {
    repo: "kubernetes-sigs/headlamp",
    number: 5876,
    kind: "pr",
    title: "frontend: ObjectEventList: Handle events without a source field",
    url: "https://github.com/kubernetes-sigs/headlamp/pull/5876",
    status: "closed",
    createdAt: "2026-05-28",
  },
  {
    repo: "swiftlang/swift-corelibs-foundation",
    number: 5486,
    kind: "pr",
    title: "NSNull: fix === returning false when both operands are nil",
    url: "https://github.com/swiftlang/swift-corelibs-foundation/pull/5486",
    status: "merged",
    createdAt: "2026-05-28",
  },
  {
    repo: "headlamp-k8s/plugins",
    number: 769,
    kind: "pr",
    title: "karpenter: implement i18n",
    url: "https://github.com/headlamp-k8s/plugins/pull/769",
    status: "merged",
    createdAt: "2026-05-28",
  },
  {
    repo: "headlamp-k8s/plugins",
    number: 768,
    kind: "pr",
    title: "KEDA: implement i18n",
    url: "https://github.com/headlamp-k8s/plugins/pull/768",
    status: "merged",
    createdAt: "2026-05-28",
  },
  {
    repo: "aaif-goose/goose",
    number: 9453,
    kind: "issue",
    title: "Built in Devin AI extension",
    url: "https://github.com/aaif-goose/goose/issues/9453",
    status: "closed",
    createdAt: "2026-05-27",
  },
  {
    repo: "swiftlang/vscode-swift",
    number: 2254,
    kind: "pr",
    title: "Reveal the task terminal when clicking the Swift build status item",
    url: "https://github.com/swiftlang/vscode-swift/pull/2254",
    status: "merged",
    createdAt: "2026-05-27",
  },
  {
    repo: "apple/swift-http-types",
    number: 124,
    kind: "pr",
    title: "Added known HTTP header field names from W3C Trace Context",
    url: "https://github.com/apple/swift-http-types/pull/124",
    status: "merged",
    createdAt: "2026-05-27",
  },
  {
    repo: "swiftlang/sourcekit-lsp",
    number: 2668,
    kind: "pr",
    title: "Add 'Add Explicit Raw Values' code action",
    url: "https://github.com/swiftlang/sourcekit-lsp/pull/2668",
    status: "merged",
    createdAt: "2026-05-26",
  },
  {
    repo: "apple/swift-openapi-runtime",
    number: 198,
    kind: "pr",
    title: "Add validating setters to OpenAPI dynamic value containers",
    url: "https://github.com/apple/swift-openapi-runtime/pull/198",
    status: "open",
    createdAt: "2026-05-26",
  },
  {
    repo: "swiftlang/swift-package-manager",
    number: 10120,
    kind: "pr",
    title: "detect @main on the same line as a block comment end",
    url: "https://github.com/swiftlang/swift-package-manager/pull/10120",
    status: "open",
    createdAt: "2026-05-25",
  },
  {
    repo: "vapor/vapor",
    number: 3463,
    kind: "pr",
    title: "Update FileIO doc examples to async API",
    url: "https://github.com/vapor/vapor/pull/3463",
    status: "closed",
    createdAt: "2026-05-25",
  },
  {
    repo: "aaif-goose/goose",
    number: 8300,
    kind: "pr",
    title: "fix: align hamburger menu with macOS traffic light buttons",
    url: "https://github.com/aaif-goose/goose/pull/8300",
    status: "merged",
    createdAt: "2026-04-04",
  },
  {
    repo: "aaif-goose/goose",
    number: 8299,
    kind: "issue",
    title: "bug: hamburger menu misaligned with macOS traffic light buttons",
    url: "https://github.com/aaif-goose/goose/issues/8299",
    status: "closed",
    createdAt: "2026-04-03",
  },
  {
    repo: "CodeEditApp/CodeEdit",
    number: 2171,
    kind: "pr",
    title: "Fix Language Servers settings page UI and search",
    url: "https://github.com/CodeEditApp/CodeEdit/pull/2171",
    status: "open",
    createdAt: "2026-03-08",
  },
  {
    repo: "microsoft/vscode",
    number: 286212,
    kind: "pr",
    title: "fix(terminal): support decimal font sizes",
    url: "https://github.com/microsoft/vscode/pull/286212",
    status: "open",
    createdAt: "2026-01-06",
  },
  {
    repo: "microsoft/vscode",
    number: 286194,
    kind: "issue",
    title: "Support decimal/floating-point values for terminal.integrated.fontSize",
    url: "https://github.com/microsoft/vscode/issues/286194",
    status: "open",
    createdAt: "2026-01-06",
  },
];
